### ISSUE TITLE
[REQ] привет, можешь пожалуйста дать не зашифрованный скрипт, пожалуйста, переведи на английский

### ISSUE THREAD

**Issue by Samthapa76** [d7KrEoL/avionics#5]
привет, можешь пожалуйста дать не зашифрованный скрипт, пожалуйста, я переведу его на английский
я расшифровал его, но на нем странный текст, просто перевести его позже, ок, не для загрузки или чего-то еще, просто для личного использования, если можешь дать не зашифрованный скрипт, это будет большой помощью, брат

**Comment by d7KrEoL** [comment]
Привет, версия исходника которая [лежит на github](https://github.com/d7KrEoL/avionics/blob/main/moonloader/SW_Avionics.lua) актуальна. Если проблема в кодировке - то можешь попробовать эту версию:
[Avionics_UTF8.txt](https://github.com/user-attachments/files/17686667/Avionics_UTF8.txt)

p.s. если будет перевод, то добавлю мультиязычность в следующей версии
